version: "3.9"
services:
  #######
  # Tails Server for Revocation support
  #######
  tails-server:
    profiles:
      - tails
    build:
      context: https://github.com/bcgov/indy-tails-server.git#main
      dockerfile: docker/Dockerfile.tails-server
    ports:
      - "6543:6543"
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /home/indy/tails-server-files
        --log-level DEBUG
    # container runs as user indy, but mount belongs to root
    # needs change in Dockerfile to fix the permissions
    user: root
    volumes:
      - tails-data:/home/indy/tails-server-files

volumes:
  tails-data:
